### Password/Username/Port Generation
import random
import os

letters = [
	'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o',
    'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D',
    'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
    'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
symbols = ['+','-','_','=']
more = ['!','#','@','$','&','*','(',')','<','>','.','%','?','^']

### Distro Information

### Daemon User (`firo`) Password Gen
def usr_passwd_gen(num):
	passwd = []
	charlist = letters+numbers+symbols+more
	for i in range(num):
		randomchar = random.choice(charlist)
		passwd.append(randomchar)
	usrpwd = "".join(passwd)
	return usrpwd

### RPC Username ###
def username_gen(num):
	u = []
	charlist = letters
	for i in range(num):
		randomchar = random.choice(charlist)
		u.append(randomchar)
	rpcname = "".join(u)
	return rpcname
### RPC Password Generator
def rpc_passwd_gen(num):
	passwd = []
	charlist = letters+numbers+symbols
	for i in range(num):
		randomchar = random.choice(charlist)
		passwd.append(randomchar)
	rpcpwd = "".join(passwd)
	return rpcpwd

### Random port generator ###

def port_gen():
	p = []
	firstchar = random.choice("12345")
	p.append(firstchar)
	for i in range(4):
		randomchar = random.choice(numbers)
		p.append(randomchar)
	randport = "".join(p)
	return randport

## sanatize

def rpc_pass(v):
    print("v_rpc_pass: "+v)
    #check that the password doesnt use "#", might want to make it more strict

def ext(v):
     print("v_ext: "+v)
    #check that its not an internal ip && ip is valid

def port(v):
	if v < 1024 and v != 22:
		print("v_port: "+v)

    #check against commonly used ports, inform user port should be above 10000 exit()

def usr(v):
	print("v_usr: "+v)
    #char only exit()  if fails

## Check if key exists 
def key_check(a):
	dir = a
	num = 0
	file = 'ed25519_firo_0'
	cond = True
	
	for root, dirs, files in os.walk(dir):
		while cond:
			if num == 100:
				print("Too many keys have been generated by this script, please check you are using all 99 of your keys!")
			elif file in files and num > 9 and num < 100:
				num+=1
				file = file[:-2]
				file = file+str(num)
			elif file in files and file[-1] == str(num):
				num+=1
				file = file[:-1]
				file = file+str(num)
			elif file in files and file+'_'+str(num) in files:
				num+=1
				file = file+'_'+str(num)
			else:
				cond = False
				return file