#!/usr/bin/env python3

### Create static ip address ###

def static_ip(dist, dist_ver, network_if):
	print("========== Creating static ip address ==========\n")
	if dist == 'debian' or ('ubuntu' and dist_ver <= '16'):
		f = open('/etc/network/interfaces', 'w')
		if 'en' in network_if:
			f.write('#Generated by Firo Masternode Startup Script\n\n#primary network interface\nauto '+network_if+'\niface '+network_if+' enp0s3 inet static\n\taddress '+lan_addr+'/'+subnet+'\n\tnetwork '+network+'\n\tbroadcast '+broadcast+'\n\tgateway '+gateway+'\n\tdns-nameserver 1.1.1.1\n\tdns-nameserver 1.0.0.1\n\n#loopback interface\nauto lo\niface lo inet loopback')
		elif 'wl' in network_if:
			print("This script currently doesn't work with wifi")
			print("==========Failed to create a static ip address!==========\n")
		elif 'tun' or 'nord':
			print("Seems like you are connected to a VPN, please disconnect and try again")
			print("==========Failed to create a static ip address!==========\n")
		else:
			print("Not able to gather required information!")
			print("==========Failed to create a static ip address!==========\n")
	elif dist == 'ubuntu' and dist_ver > '16': 
		f = open("/etc/netplan/01-netcfg.yaml", "w")
		if "en" in network_if:
			f.write('#Created by Firo Masternode Startup Script\n\nnetwork:\n\tversion: 2\n\trenderer: NetworkManager\n\tethernets:\n\t\t'+network_if+':\n\t\t\taddresses:\n\t\t\t\t- '+lan_addr+'\n\t\t\tnameservers:\n\t\t\t\taddresses: [1,1,1,1, 1.0.0.1]\n\t\t\troutes:\n\t\t\t\t- to: default\n\t\t\t\t  via:'+gateway)
		elif "wl" in network_if:
			print("This script currently doesn't work with wifi")
			print("==========Failed to create a static ip address!==========\n")
		elif 'tun' or 'nord':
			print("Seems like you are connected to a VPN, please disconnect and try again after disconnecting")
			print("==========Failed to create a static ip address!==========\n")
		else:
			print("Not able to gather required information!")
			print("==========Failed to create a static ip address!==========\n")
	else:
		print("Static IP configuration only avilable for Debian based servers.")
		print("==========Failed to create a static ip address!==========\n")


